### ISSUE TITLE
Prevent config file from being auto-overwritten with resolved paths

### ISSUE THREAD

**Issue by hazimyussof** [sdaqo/anipy-cli#274]
I'm running into a problem where `anipy-cli` automatically overwrites my config file every time I run the program.

I want to have my files synced on different systems, but since the paths are different for each of them, I use an environment variable. But it just keeps reverting back to the default one on each system every time I run the program, how do I prevent this from happening?

**Windows would default to**:
```yaml
user_files_path: C:\Users\[user]\AppData\Local\anipy-cli
download_folder_path: C:\Users\[user]\AppData\Local\anipy-cli\download
seasonal_dl_path: C:\Users\[user]\AppData\Local\anipy-cli\download\seasonals
```

**MacOS would default to**:
```yaml
user_files_path: /Users/[user]/Library/Application Support/anipy-cli
download_folder_path: /Users/[user]/Library/Application Support/anipy-cli/download
seasonals_dl_path: /Users/[user]/Library/Application Support/anipy-cli/download/seasonals
```

**What I want to do**:
```yaml
user_files_path: ${ANIPY_FILES}
download_folder_path: ${ANIPY_FILES}/download
seasonals_dl_path: ${ANIPY_FILES}/download/seasonals
```
