### ISSUE TITLE
Feature Request: Option to download the current episode from episode control menu

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#91]
There are times when the internet connection is unstable and stream keeps buffering. It would be handy if there was an option in the Now Playing menu to download the current episode instead.

The current workaround is to either print the stream url and use yt-dlp to download the file but then manually rename and move.
Or exit the current session and open it in Download Mode and search for the episode to download. Both of which are slight annoyance to accomplish the task.

**Comment by sdaqo** [comment]
A good idea. Implemented it. I also implemented a option you can set (auto_open_dl_defaultcli) in the config that auto opens the file after the download. Have fun.

**Comment by Prashanthvsdvn** [comment]
Hey! Thanks for the immediate commit. The download option works as intended. However, the option to auto open after download doesn't. 

Sadly, I don't have any trace back or outputs that I can post it for debugging. It just doesn't auto opens after download.

However, when I try to re-download the episode, I can see `Skipping already existing` for a split second. 
Let me know, if I can do anything to sort this issue out and we can close this.

**Comment by Dabbing-Guy** [comment]
> However, when I try to re-download the episode, I can see Skipping already existing for a split second.

So, the downloading feature works. You got this message because the anime you were trying to download was already in you downloads file.

**Comment by sdaqo** [comment]
Yes, the player is probably not opening because either the option is not correctly set in the config or it's a windows problem, since it works fine on my Linux machine.

**Comment by Dabbing-Guy** [comment]
@Prashanthvsdvn can you send us your config file?

**Comment by Prashanthvsdvn** [comment]
> > However, when I try to re-download the episode, I can see Skipping already existing for a split second.
> 
> So, the downloading feature works. You got this message because the anime you were trying to download was already in you downloads file.

Yes, I was just trying to trigger the auto play option after the download.

**Comment by Prashanthvsdvn** [comment]
> @Prashanthvsdvn can you send us your config file?

```yaml
anipy_cli_folder : 'C:\Users\Prashanth\.anipy-cli'
download_folder_path : 'D:\Videos\Anime'
download_name_format : '{show_name}_{episode_number}.mp4'
download_remove_dub_from_folder_name : False
dc_presence : True
player_path: 'mpv'
auto_open_dl_defaultcli: True
```
